# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20141124_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='draft',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='draftin.Draft'),
        ),
    ]
