# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='credits',
            field=models.TextField(blank=True, default=''),
        ),
    ]
