# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
