# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_facebook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='story',
            field=models.TextField(blank=True, default=''),
        ),
    ]
